# Generated by Django 5.1 on 2024-09-17 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlightNumber', models.CharField(max_length=10)),
                ('OperatingAirlines', models.CharField(max_length=10)),
                ('DepartureCity', models.CharField(max_length=10)),
                ('ArivalCity', models.CharField(max_length=10)),
                ('DateOfDeparture', models.DateField()),
                ('EstimatedTimeOfDeparture', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('MiddleName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('PhoneNumder', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightApp.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightApp.passenger')),
            ],
        ),
    ]
