# Generated by Django 5.1 on 2024-09-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='PhoneNumder',
            field=models.CharField(max_length=10),
        ),
    ]
