# Generated by Django 5.1 on 2024-09-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0002_alter_passenger_phonenumder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='PhoneNumder',
            new_name='PhoneNumber',
        ),
    ]
